### PR TITLE
add push notification for when a product gets a suggested collection …

### PR DESCRIPTION
**Pull request by osaisacson**
…date

### CODE REVIEW

**Comment by osaisacson** [comment]
Hey @karlmarxlopez  I'm adding some more push notifications. Just checking in with you to see if adding them as in this PR is a good way forward, or if you suggest another approach.

**Comment by SpaghettiC0des** [comment]
Yup, I think this is the best approach. Are you going to add cloud functions only in this PR or push notification handlers on the app also?

**Comment by SpaghettiC0des** [comment]
I have just added a notification listener that will vibrate when receiving a PN. There's no functionality(yet) like navigating to a certain screen when a notification is opened, but I can help you implement that @osaisacson

**Comment by osaisacson** [comment]
Ok, great! It is enough to have the PN vibration for now, lets do the added functionality (go to page, etc) later when the other, more crucial parts of the app and testing are done. So for this PR we can merge?

**Review by SpaghettiC0des — APPROVED** [review]

**Review by SpaghettiC0des — APPROVED** [review]

**Review by SpaghettiC0des — APPROVED** [review]

**Comment by SpaghettiC0des** [comment]
@osaisacson All good. Merging...

**Pull request merged**
